---
agent_config_yaml: |
  node-name: {{ inventory_hostname }}
  node-ip: {{ ansible_host }}
  flannel-iface: {{ lan_interface }}
  {% if k3s_worker_node_labels | length > 0 %}
  node-label:
  {% for label in k3s_worker_node_labels %}
    - "{{ label }}"
  {% endfor %}
  {% endif %}
