---
validation_control_plane_name: "{{ groups['control_plane'][0] }}"
validation_worker_names: "{{ groups['workers'] }}"
validation_workload_node_name: "{{ k3s_workload_node_name }}"
validation_ingress_node_names: "{{ k3s_ingress_node_names }}"
validation_node_ready_timeout: 120s
validation_smoke_namespace: lab-demo
validation_smoke_label: app=nginx-smoke
validation_required_load_balancer_containers:
  - k3s-haproxy
  - power-grafana
  - power-prometheus
