---
all:
  children:
    k3s_cluster:
      children:
        server:
          hosts:
            server-tang2:
              ansible_host: 192.168.30.44
              ansible_user: node
              lan_interface: wlx347de4475af5
        agent:
          hosts:
            server-tang4:
              ansible_host: 192.168.30.35
              ansible_user: node
              lan_interface: wlx58044f3fedb4
      vars:
        ansible_port: 22
        ansible_become: true
        ansible_ssh_private_key_file: /home/monitor/.ssh/k3s_ansible_ed25519
        k3s_version: v1.36.4+k3s1
        api_endpoint: 192.168.30.45
        api_port: 6443
        cluster_context: k3s-homelab
        kubeconfig: /home/monitor/.kube/config
        user_kubectl: true
        k3s_server_config_mode: "0600"
        server_config_yaml: |
          node-name: server-tang2
          node-ip: 192.168.30.44
          flannel-iface: wlx347de4475af5
          cluster-cidr: 10.42.0.0/16
          service-cidr: 10.43.0.0/16
          tls-san:
            - 192.168.30.45
          secrets-encryption: true
          write-kubeconfig-mode: "0600"
          node-taint:
            - "node-role.kubernetes.io/control-plane=true:NoSchedule"
        agent_config_yaml: |
          node-name: server-tang4
          node-ip: 192.168.30.35
          flannel-iface: wlx58044f3fedb4
          node-label:
            - "svccontroller.k3s.cattle.io/enablelb=true"
            - "svccontroller.k3s.cattle.io/lbpool=ingress"

    load_balancer:
      hosts:
        server-tang3:
          ansible_connection: local
          ansible_user: monitor
          ansible_become: true
          ansible_host: 192.168.30.45
          lan_interface: wlp2s0
          haproxy_image: haproxy:3.2.24-alpine3.24
          haproxy_api_backend: 192.168.30.44
          haproxy_ingress_backend: 192.168.30.35
